[package]
name = "blub_indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
tantivy = { git = "https://github.com/quickwit-oss/tantivy/", tag="0.22.0" }

[[bin]]
name = "blub_indexer"
path = "blub_indexer.rs"
